module1-task3 | divided into components
htmlacademy-ecmascript/1849247-big-trip-16 pull request #3
Opened 2021-11-28 17:00 UTC by ifom1500

2021-11-29 04:33 UTC, AlexMasterov requested changes

2021-11-29 04:33 UTC, AlexMasterov commented on public/index.html
> +
<details>
<summary>public/index.htm</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/8ee99221f17a845a7067e7ad54d9eaa29168530f/public/index.html#L24-L27
</details>

См. ТЗ:
> При переключении на экран статистики фильтрация сбрасывается на состояние `Everything`, **а сами фильтры скрываются**

Лучше лучше забрать эту разметку в форму фильтрации или тоже создавать отдельной функцией, а далее view-компонентом в роле _контейнера_. Потом это поможет полностью скрыть элемент компонента с фильтрами.

> По теме курса работа с DOM браузером должна происходить через интерфейсы компонентов, а не в обход, через вывозы `document.querySelector`, работая с элементами напрямую

2021-11-29 04:33 UTC, AlexMasterov commented on src/main.js
> +  BEFOREBEGIN: 'beforebegin',
Читаемость:
```diff
- BEFOREBEGIN: 'beforebegin',
+ BEFORE_BEGIN: 'beforebegin',
```

2021-11-29 04:33 UTC, AlexMasterov commented on public/index.html
> +
<details>
<summary>public/index.html</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/8ee99221f17a845a7067e7ad54d9eaa29168530f/public/index.html#L36-L42
</details>

Лучше создавать эту разметку отдельной функцией.

> Не критично

2021-11-29 04:33 UTC, AlexMasterov commented on public/index.html
> +
<details>
<summary>public/index.html</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/8ee99221f17a845a7067e7ad54d9eaa29168530f/public/index.html#L30
</details>

<details>
<summary>markup/stats.html</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/8ee99221f17a845a7067e7ad54d9eaa29168530f/markup/stats.html#L51-L68
</details>

Функциb (и далее компонентs) для создания этой разметки можно заготовить заранее.

2021-11-29 04:33 UTC, AlexMasterov commented on src/main.js
> +eventsElement.append(eventsListElement);
Разметкf точки маршрута создается с разметкой: (`<li>`)

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/8ee99221f17a845a7067e7ad54d9eaa29168530f/markup/list.html#L100


<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/8ee99221f17a845a7067e7ad54d9eaa29168530f/src/main.js#L39-L41
</details>

Вместо этого также следовало создать _отдельный_ view-компонент (контейнер) для разметки: (`<ul>`)

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/8ee99221f17a845a7067e7ad54d9eaa29168530f/markup/list.html#L99

Потом будет неудобно работать с элементами этой разметки и скорее всего придаться переделывать.

> Это также расходится в примером разбиения разметки на компоненты из демо проекта, а подобная прямая работа с DOM идет мимо темы курса

2021-11-29 04:33 UTC, AlexMasterov commented on src/view/filters-view.js
> +export const createFiltersComponent = () => (
<details>
<summary>view/filters-view.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/8ee99221f17a845a7067e7ad54d9eaa29168530f/src/view/filters-view.js#L1-L20
</details>

const createFilters`Component` = () => (

Функция создает и возвращает шаблон с разметкой, а не сам компонент — это не фабрика, а компонентов еще нет.

> С появлением класса для компонента эта функция станет вспомогательной, чтобы отдельной создать шаблон. В крайнем случае такую функцию можно сделать методом класса, но никак не (конструктором) самого компонента

[`Б 10`](https://up.htmlacademy.ru/ecmascript/16/criteries#b10)
> Название функции или метода должно быть глаголом и **соответствовать действию**, которое выполняет функция или метод

Нужно подобным образом исправить _во всем проекте_:

```diff
- export const createFiltersComponent = () => (
+ export const createFiltersTemplate = () => (
```

2021-11-30 16:24 UTC, ifom1500 commented on src/main.js
> +  BEFOREBEGIN: 'beforebegin',
Исправил

2021-11-30 17:22 UTC, ifom1500 commented on public/index.html
> +
Пока положил разметку `<div class="trip-controls__filters"></div>` в форму фильтрации, в будущем вынесу в компонент

2021-11-30 20:06 UTC, ifom1500 commented on public/index.html
> +
Подготовил функции, возвращающие данные разметки

2021-11-30 20:07 UTC, ifom1500 commented on public/index.html
> +
Добавил функцию для возвражения данной разметки

2021-11-30 20:08 UTC, ifom1500 commented on src/main.js
> +eventsElement.append(eventsListElement);
Добавил функцию для возвражения данной разметки

2021-11-30 20:23 UTC, ifom1500 commented on public/index.html
> +
Прошу не обращать внимание на огромное количество комментариев. Позже подчищу обязательно.

2021-11-30 20:25 UTC, ifom1500 commented on public/index.html
> +    <!-- headerElement -->
Прошу не обращать вимание на огромное количество поясняющих для себя комментариев. Позже подчищу.

2021-11-30 20:28 UTC, ifom1500 commented on src/main.js
> +const tripEventsElement = mainElement.querySelector('.trip-events');
Такая конструкция, которая сначала отрисовывает "компонент", а затем ищет его на странице мне кажется не совсем надежной. Но пока не придумал лучшего способа. Это корректное решение?

2021-11-30 20:33 UTC, ifom1500 commented on src/main.js
> +const mainContainerElement = mainElement.querySelector('.page-main__container');
На странице приложения в данном контейнере `mainContainerElement` появляется "() => ``". Не смог понять откуда это. Буду рад подсказке :)
![Screenshot_1](https://user-images.githubusercontent.com/77317082/144123453-0396c5fd-964a-426d-9c94-137c14fd4a4a.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/77317082/144123488-b7417ec8-614a-4692-987f-4207352e9d94.jpg)

2021-12-01 03:49 UTC, AlexMasterov commented on src/main.js
> +const mainContainerElement = mainElement.querySelector('.page-main__container');
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/be9f5b3c0efb4805fcbe3129905e8abae14bad06/src/main.js#L47
</details>

renderTemplate(mainContainerElement, `createTripEventsTemplate`, RenderPosition.AFTER_BEGIN);

Если вместо результата вызова функции, в качестве _строки_ (или в операции со _строкой_) использовать саму функцию, то для этого движком через неявный вызов [Function.p.`toString`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Function/toString) будет получено её строковое представление.

2021-12-01 03:56 UTC, AlexMasterov commented on src/main.js
> +const tripEventsElement = mainElement.querySelector('.trip-events');
> Но пока не придумал лучшего способа. Это корректное решение?

На текущем этапе и для этого задания такое решение допустимо.

Это _временное_ решение, которое далее будет дорабатываться на лайвах и через требования следующих заданий.

2021-12-01 03:57 UTC, merged

2021-12-01 15:58 UTC, ifom1500 commented on src/main.js
> +const mainContainerElement = mainElement.querySelector('.page-main__container');
исправил, спасибо :)