Module2 task1
htmlacademy-ecmascript/1849247-big-trip-16 pull request #4
Opened 2021-12-05 22:12 UTC by ifom1500

2021-12-05 22:19 UTC, ifom1500 commented
Добрый вечер! Создал PR по незавершенному заданию, так как пока застрял на месте и не могу дальше продвинуться. Просьба посмотреть что правильно, какие есть ошибки. И хотел бы проконсультироваться вечером, разобрать что делать дальше. Запрос на консультацию создал.
[Голосовая консультация #347085](https://up.htmlacademy.ru/profession/react/8/ecmascript/requests/347085)

2021-12-07 15:36 UTC, AlexMasterov requested changes
Жду изменений в коде по результатам консультации.

2021-12-07 15:36 UTC, AlexMasterov commented on src/view/trip-point-view.js
> +      <h3 class="event__title">${type[0].toUpperCase()}${type.slice(1)} ${destination}</h3>
<details>
<summary>view/form-edit-view.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/81d53240348c9412cd8151b448d98ad38417c45a/src/view/form-edit-view.js#L148
</details>
<details>
<summary>view/trip-point-view.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/81d53240348c9412cd8151b448d98ad38417c45a/src/view/trip-point-view.js#L50
</details>

Д11
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции или вынесены из условий

2021-12-07 15:36 UTC, AlexMasterov commented on src/view/trip-point-view.js
> +dayjs.extend(duration);
Желательно работу с библиотекой `dayjs` скрыть за интерфейсом функций, которые разместить в отдельном модуле.

2021-12-07 15:36 UTC, AlexMasterov commented on src/view/form-edit-view.js
> +const createEventTypeListTemplate = () => (
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/145058632-d5129ea8-2772-421d-854a-b3b4945ae2dd.png)

</details>

Выбор типа в иконке не совпадает с выбором типа в списке.

Желательно реализовать в этом задание.

2021-12-07 15:36 UTC, AlexMasterov commented on src/view/form-edit-view.js
> +const createEventTypeListTemplate = () => (
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/145058850-723bade5-f886-497d-b1c6-4f0d2691d2c6.png)

</details>

Нужно убрать `;` из списка выбора типов 😃

2021-12-08 00:23 UTC, ifom1500 commented on src/view/form-edit-view.js
> +const createEventTypeListTemplate = () => (
Исправил

2021-12-08 00:24 UTC, ifom1500 commented on src/view/trip-point-view.js
> +      <h3 class="event__title">${type[0].toUpperCase()}${type.slice(1)} ${destination}</h3>
Повторяющийся код вынес в отедльную функцию и отдельный модуль

2021-12-08 00:25 UTC, ifom1500 commented on src/view/trip-point-view.js
> +dayjs.extend(duration);
Локализовал всю работу с библиотекой dayjs в отдельном модуле

2021-12-08 00:45 UTC, ifom1500 commented on src/view/form-edit-view.js
> +const createEventTypeListTemplate = () => (
Пока добавил функцию в main.js. Думаю, дальше она  должна быть в составе компонента формы создания или редактирования точки маршрута

2021-12-08 01:00 UTC, AlexMasterov approved these changes
Пожалуйста, мелкие замечания в остатке исправь при выполнении следующего задания.

2021-12-08 01:01 UTC, merged

2021-12-08 21:18 UTC, ifom1500 commented on src/view/form-edit-view.js
> +  const destinationList = destinations.map(({ name }) => `<option value="${name}"></option>`).join('');
исправил

2021-12-08 21:19 UTC, ifom1500 commented on src/view/form-edit-view.js
> +  const offersSectionTemlate = createOffersSectionTemlate(renderedOffers);
исправил опечатку

2021-12-08 21:25 UTC, ifom1500 commented on src/utils/utils.js
> +const makeCapLetter = (word) => `${word[0].toUpperCase()}${word.slice(1)}`;
Переименовал функцию в capitalise().

> Для названия значений используются английские существительные
Но это же функция, а функции необходимо именовать как глаголы?

2021-12-08 21:30 UTC, ifom1500 commented on src/main.js
> +const eventTypeBtnIcon = eventTypeBtn.querySelector('.event__type-icon');
Исправил

2021-12-08 21:35 UTC, ifom1500 commented on src/main.js
> +const eventTypeBtnIcon = eventTypeBtn.querySelector('.event__type-icon');
Исправил

2021-12-08 21:41 UTC, ifom1500 commented on src/view/form-edit-view.js
> +  const dateTo = parseDate(dateToObject);
Согласен.. Исправил, спасибо!