Module3 task1
htmlacademy-ecmascript/1849247-big-trip-16 pull request #5
Opened 2021-12-12 18:17 UTC by ifom1500

2021-12-12 18:26 UTC, ifom1500 commented
Добрый вечер!
Выходит такая ошибка, но на работу не влияет. Это что-то связано со сменой иконки типа точки и закрытием формы, но закономерность не смог установить.
![image](https://user-images.githubusercontent.com/77317082/145724643-5bba36f1-bf8c-439f-9187-8017cfa62ab7.png)

2021-12-12 22:44 UTC, AlexMasterov requested changes

2021-12-12 22:44 UTC, AlexMasterov commented on src/main.js
> +    typeGroupElement.addEventListener('change', onChangeTypeGroupElement);
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/d1dd3932c141dad5bb024322f52aa078eb19b493/src/main.js#L35-L44
</details>

Это можно удалить.

На этом интенсиве подобная задача решается иначе. Изучай демо проект и жди след. заданий.

2021-12-12 22:44 UTC, AlexMasterov commented on src/main.js
> +const TripEventsComponent = new TripEventsView();
`T`ripEventsComponent

Б3
> Название переменных, параметров, свойств и методов начинается со строчной буквы и записываются в нотации `camelCase`

2021-12-12 22:44 UTC, AlexMasterov commented on src/main.js
> +  const EventListComponent = new EventListView();
`E`ventListComponent

Б3
> Название переменных, параметров, свойств и методов начинается со строчной буквы и записываются в нотации `camelCase`

2021-12-12 22:44 UTC, AlexMasterov commented on src/main.js
> +  // render(EventListComponent.element, new FormCreateView(tripPoints[0], destinations, allOffers).element, RenderPosition.BEFORE_END);
`//`

Нужно удалить.

2021-12-12 22:44 UTC, AlexMasterov commented on src/view/events-list-view.js
> +export default class EventListView {
`events`-list-view.js !== `Event`ListView

> event`s`-list-view.js

Б27
> Имя модуля должно соответствовать его содержимому

> Например, если в модуле лежит класс `GameView`, то и имя модуля должно быть `game-view`.js

2021-12-12 22:44 UTC, AlexMasterov commented on src/view/form-edit-view.js
> +import { allOffers } from '../mock/trip-point.js';
Сейчас модуль компонента стал напрямую работать с тест. данными, которые вскоре будут удалены, а сам список предложений стал отображается неправильно.

<details>
<summary>view/form-create-view.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/d1dd3932c141dad5bb024322f52aa078eb19b493/src/view/form-create-view.js#L1
</details>

Напомню, что компоненты должны работать с данными, [как с настоящими](https://up.htmlacademy.ru/ecmascript/16/module/2/questions#:~:text=%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5%20%22%D0%BA%D0%B0%D0%BA%20%D0%BD%D0%B0%D1%81%D1%82%D0%BE%D1%8F%D1%89%D0%B8%D0%B5%22%20%D0%B8%20%D0%BD%D0%B0%D1%83%D1%87%D0%B8%D1%82%D1%8C%20%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D1%8B%20%D0%B8%D1%85%20%D0%BF%D1%80%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D1%82%D1%8C).

<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/145732026-be844183-5f4a-4404-ad8c-89864dc4b84c.png)

</details>

Список доступных предложений для всех типов `allOffers` следует передать отдельным аргументом при создании экземпляра класса (объекта) `FormCreateView`, а в его функцию для создании шаблона `createFormCreateTemplate` передать список предложений _для конкретного типа_ (= `point.type`), который нужно прежде найти/получить из `allOffers`.

Нужно разобраться и исправить.

2021-12-12 22:44 UTC, AlexMasterov commented on src/main.js
> +// import FormCreateView from './view/form-create-view.js'; // пока не используем
> пока не используем

Лучше попробуй объединить оба компонента в один 😃

> Как вариант, можешь ввести некоторое состояние, например, `mode`, которое использовать для определения режима формы: `this.#mode === 'EDIT'` и т.п.

2021-12-12 22:44 UTC, AlexMasterov commented on src/main.js
> +    if (evt.key === 'Escape' || evt.key === 'Esc') {
`Escape`, `Esc`

На защите проекта могут придраться.

Б5
> Названия констант (постоянных значений) написаны прописными (заглавными) буквами


<details>
<summary>Покажи что можно сделать</summary>

```js
// utils/dom-event.js
const ESCAPE_KEYS = ['Escape', 'Esc'];

const isEscapeEvent = (evt) => ESCAPE_KEYS.includes(evt.key);
```
```diff
- if (evt.key === 'Escape' || evt.key === 'Esc') {
+ if (isEscapeEvent(evt)) {
```
</details>

2021-12-12 22:44 UTC, AlexMasterov commented on src/view/new-event-button-view.js
>  export const createNewEventButtonTemplate = () => ('<button class="trip-main__event-add-btn  btn  btn--big  btn--yellow" type="button">New event</button>');
В этом случае скобки `()`  для группировки выражений избыточны.

2021-12-12 22:44 UTC, AlexMasterov commented on src/view/new-event-button-view.js
>  export const createNewEventButtonTemplate = () => ('<button class="trip-main__event-add-btn  btn  btn--big  btn--yellow" type="button">New event</button>');
<details>
<summary>view/new-event-button-view.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/d1dd3932c141dad5bb024322f52aa078eb19b493/src/view/new-event-button-view.js#L3
https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/d1dd3932c141dad5bb024322f52aa078eb19b493/src/view/new-event-button-view.js#L5
</details>

`export` const createNewEventButtonTemplate

Б28
> Из одного модуля экспортируется не больше _одного_ класса. Класс всегда экспортируется как `default`

2021-12-12 22:45 UTC, AlexMasterov commented on src/render.js
> +  return newElement.firstChild; // 3
```diff
- return newElement.firstChild;
+ return newElement.firstElementChild;
```

2021-12-12 22:49 UTC, AlexMasterov commented
> Добрый вечер! Выходит такая ошибка, но на работу не влияет. Это что-то связано со сменой иконки типа точки и закрытием формы, но закономерность не смог установить. ![image](https://user-images.githubusercontent.com/77317082/145724643-5bba36f1-bf8c-439f-9187-8017cfa62ab7.png)

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/d1dd3932c141dad5bb024322f52aa078eb19b493/src/main.js#L35-L44
</details>

Перерисовка компонентов будет реализована иначе, а твой вариант, _с доработкой_, может быть использован _после_ в качестве её оптимизации. Пожалуйста, пока изучай демо проекта и жди след. заданий.

2021-12-12 22:50 UTC, AlexMasterov commented on src/view/form-edit-view.js
>    });
<details>
<summary>view/form-edit-view.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/d1dd3932c141dad5bb024322f52aa078eb19b493/src/view/form-edit-view.js#L106
https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/d1dd3932c141dad5bb024322f52aa078eb19b493/src/view/form-edit-view.js#L108-L111
</details>

Можно избавится от переменной:

```diff
- const isChecked = tripOffers.some(({ id }) => id === offer.id);
```

```diff
- isChecked,
+ isChecked: tripOffers.some(({ id }) => id === offer.id),
```

2021-12-13 04:09 UTC, AlexMasterov commented on src/main.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/145750975-85e47cb0-d2ef-40e1-a29c-f36768ffd989.png)

</details>

Если закрыть форму редактирования нажатием на кнопку с изображением "Стрелка вверх" в правом углу, то на `document` остается обработчик для `keydown`.

Б36
> Обработчики события добавляются и удаляются своевременно

2021-12-13 18:39 UTC, ifom1500 commented on src/render.js
> +// const renderElement = (container, element, place) => {
Удалил

2021-12-13 18:39 UTC, ifom1500 commented on src/render.js
> +const createElement = (template) => {
Удалил

2021-12-13 18:44 UTC, ifom1500 commented on src/main.js
> +    typeGroupElement.addEventListener('change', onChangeTypeGroupElement);
Удалил

2021-12-13 18:45 UTC, ifom1500 commented on src/main.js
> +const TripEventsComponent = new TripEventsView();
Исправил

2021-12-13 18:46 UTC, ifom1500 commented on src/main.js
> +  const EventListComponent = new EventListView();
Исправил

2021-12-13 18:50 UTC, ifom1500 commented on src/main.js
> +  // render(EventListComponent.element, new FormCreateView(tripPoints[0], destinations, allOffers).element, RenderPosition.BEFORE_END);
Удалил

2021-12-13 18:58 UTC, ifom1500 commented on src/view/events-list-view.js
> +export default class EventListView {
Переименовал класс в `EventsListView` в модуле `events-list-view.js` и далее по коду приложения

2021-12-13 19:06 UTC, ifom1500 commented on src/main.js
> +    if (evt.key === 'Escape' || evt.key === 'Esc') {
Вынес вспомогательный код в модуль `utils.js`
В `main.js` импортировал более абстрактную функцию `isEscapeEvent(evt)`

2021-12-13 19:12 UTC, ifom1500 commented on src/view/new-event-button-view.js
>  export const createNewEventButtonTemplate = () => ('<button class="trip-main__event-add-btn  btn  btn--big  btn--yellow" type="button">New event</button>');
Удалил скобки в обоих функциях

2021-12-13 19:12 UTC, ifom1500 commented on src/view/new-event-button-view.js
>  export const createNewEventButtonTemplate = () => ('<button class="trip-main__event-add-btn  btn  btn--big  btn--yellow" type="button">New event</button>');
Удалил

2021-12-13 19:18 UTC, ifom1500 commented on src/render.js
> +  return newElement.firstChild; // 3
Исправил. Согласен, что безопаснее использовать `firstElementChild`, который возвращает первый **элемент**, а не узел.

2021-12-13 19:30 UTC, ifom1500 commented on src/view/form-edit-view.js
>    });
Перенес опеределенние совпадения `isChecked` в свойство объекта

2021-12-13 23:06 UTC, ifom1500 commented on src/view/form-edit-view.js
> +import { allOffers } from '../mock/trip-point.js';
Решение нашел, но, думаю, что можно сделать лучше. Пока расспишу, если есть ошибки в логике, то прошу указать.

Сейчас мой **`allOffers`** - это массив объектов, в которых есть 2 поля `type` и массив `offers` для конктретного типа предложенний.

1. Импортирую `allOffers` из моков в main.js, откуда его передаю в Класс в качестве параметра

`const pointEditComponent = new FormEditView(point, destinations, allOffers);`

2. Передаю `allOffers` в приватное поле `this.#allOffers` (в конструкторе) -> передаю в шаблон полностью весь массив.
Возможно здесь уже можно взять из массива `allOffers` объект нужного мне типа (то есть типа, совпадающего с типом маршрута), но не знаю как это сделать из класса.

<details>
  <summary>Пример кода</summary>

```
export default class FormEditView {
  #element = null;
  #point = null;
  #destination = null;
  #allOffers = null;

  constructor(point, destination, **offers**) {
    this.#point = point;
    this.#destination = destination;
    this.#allOffers = offers;
  }
...
  get template() {
    return createFormEditTemplate(this.#point, this.#destination, this.#allOffers);
  }
```

</details>

3. Принимаю этот массив в шаблоне `const createFormEditTemplate = (point, destinations, allOffers)`

4. Ищу тот объект из массива `allOffers`, тип которого совпадает с типом точки маршрута
Так как может быть только один объект, то использую метод _find_

`const searchOffers = (offers) => offers.find((item) => item.type === type);`

Записываю в переменную, из которой смогу добраться до свойства `offers`

`const typeOffers = searchOffers(allOffers);`

5. Теперь проверяю совпадает ли id из офферов точки маршрута с id `typeOffers` и если да - то указываю свойство `isChecked` - в приложении - это уже отмеченные предложения

<details>
  <summary>Пример кода</summary>

```
  typeOffers.offers.forEach((offer) => {
    renderedOffers.push({
      ...offer,
      isChecked: tripOffers.some(({ id }) => id === offer.id),
    });
  });
```

</details>

2021-12-14 04:30 UTC, AlexMasterov commented on src/view/form-edit-view.js
> +import { allOffers } from '../mock/trip-point.js';
> Возможно здесь уже можно взять из массива `allOffers` объект нужного мне типа (то есть типа, совпадающего с типом маршрута), но не знаю как это сделать из класса

В простую функцию для создания шаблона `createFormEditTemplate` лучше передавать уже подготовленные структуры. Для этого в демо проекте большая часть логики будет вынесена в класс, т.е. "поднята" на уровень выше.

Таким образом вычислять `typeOffers` лучше вне функции `createFormEditTemplate`, а ей передавать уже его готовым. Еще лучше готовым передавать сам `renderedOffers` 😃

С появлением моделей всё подобное вычисление можно будет разместить в модели для `Offers`. Сейчас можно это делать в самом классе, а если совсем сложно, то оставить в функции шаблона.

2021-12-14 04:39 UTC, AlexMasterov commented on src/view/form-edit-view.js
> +import { allOffers } from '../mock/trip-point.js';
> Сейчас мой `allOffers` - это массив объектов, в которых есть 2 поля type и массив offers для конктретного типа предложенний

Предлагал на его основе создать объект-словарь (= `{ [pointType]: [{}, {}] }`) и показывал для этого код. Тогда получать `typeOffers` можно будет без цикла, за константное `O(1)`, вместо `O(N)` с циклом по массиву. Но такая оптимизация выполняется по желанию.

Также советовал логику получения этих массивов вынести в функции с говорящим названием. Сейчас вся логика буквально валяется в функции шаблона (и скорее всего в таком виде переедет в методы класса). Но это тоже по желанию.

2021-12-14 22:59 UTC, ifom1500 commented on src/view/form-edit-view.js
> +import { allOffers } from '../mock/trip-point.js';
> передавать уже его готовым. Еще лучше готовым передавать сам renderedOffers

Выполнил: передаю в шаблон сразу массив `renderedOffers`, который переименовал в более говорящее название `renderedWithCheckboxOffers`

---
> создать объект-словарь

Выполнил: реализация в коммите [0545bb7 - module3-task1 | fix allOffers as map adapter](https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/pull/5/commits/0545bb7b443a4cd26d9b895a9ab5374377a1e3a6)

---
> логику получения этих массивов вынести в функции с говорящим названием

Выполнил: коммит [426111f - module3-task1 | extract function from template form-edit](https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/pull/5/commits/426111f73bef36f3d73b09d86b8b511b28e9b6c8)

---
Приношу извинения, что сразу не выполняю рекомендации с голосовой консультации. Пока не сразу доходит для чего это нужно и как реализовать, нужно время на усвоение 😀

2021-12-14 23:28 UTC, ifom1500 commented on src/main.js
> +
Исправил

2021-12-16 23:15 UTC, ifom1500 commented on src/main.js
> +// import FormCreateView from './view/form-create-view.js'; // пока не используем
Выполнил: коммит [module3-task1 | merge create and edit forms into a single component](https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/pull/5/commits/1e3bab28e0b8a18c88990fbf5568da74f69e6d99)

2021-12-16 23:41 UTC, AlexMasterov commented
👍🏻

2021-12-16 23:42 UTC, merged