Module4 task1
htmlacademy-ecmascript/1849247-big-trip-16 pull request #6
Opened 2021-12-19 00:41 UTC by ifom1500

2021-12-19 02:24 UTC, AlexMasterov requested changes

2021-12-19 02:24 UTC, AlexMasterov commented on src/utils/constants.js
> +export const Mode = {
export const `Mode` = {

`Mode` _чего_? 

Слишком общие название, которое находится в общий для всего проекта модуле `utils/constants`.js.

2021-12-19 02:24 UTC, AlexMasterov commented on src/utils/constants.js
> +export const Mode = {
<details>
<summary>utils/constants.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/a5e792847fe814a261082a410fe213e80e60144d/src/utils/constants.js#L40-L43
</details>

CREATE_MODE: `true`
EDIT_MODE: `false`

Б7
> Значения перечислений объявлены как константы

> См. пример _перечисления_ в описание критерия и демо проекте

2021-12-19 02:24 UTC, AlexMasterov commented on src/utils/constants.js
> +export const Mode = {
<details>
<summary>utils/constants.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/a5e792847fe814a261082a410fe213e80e60144d/src/utils/constants.js#L40-L43
</details>

 export const `Mode` = { 
   CREATE_`MODE`: true, 
   EDIT_`MODE`: false,

🤔

Б16
> Сложные составные константы собираются в перечисления `Enum`

> См. пример _перечисления_ в описание критерия и демо проекте

2021-12-19 02:24 UTC, AlexMasterov commented on src/utils/constants.js
> +export const POINT_COUNT = 3;
Это нужно только для тест. данных и на время их наличия.

После получения данных с сервера этот код станет мертвым и таким нарушит критерий Б18.

2021-12-19 02:24 UTC, AlexMasterov commented on src/view/abstract-view.js
> +    if (!this.#element) {
<details>
<summary>AbstractView</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/a5e792847fe814a261082a410fe213e80e60144d/src/view/abstract-view.js#L4
https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/a5e792847fe814a261082a410fe213e80e60144d/src/view/abstract-view.js#L25-L26
</details>

```diff
- if (!this.#element) {
+ if (this.#element === null) {
```

2021-12-19 02:24 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
>  const getRenderedWithCheckboxOffers = (offersToRender, offersFromPoint) => {
<details>
<summary>view/form-create-edit-view.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/a5e792847fe814a261082a410fe213e80e60144d/src/view/form-create-edit-view.js#L6-L7
</details>

 const getRenderedWithCheckboxOffers = (`offersToRender`, `offersFromPoint`) => { 
   const renderedOffers = offersToRender.reduce((`array`, offer) => { 

Б8
> Массивы названы существительными во множественном числе

2021-12-19 02:24 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
>    isModeCreate = null;
isModeCreate = `null`;

this.`isModeCreate` будет хранить _булево_ значение, а не _объект_.

2021-12-19 02:24 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
>      this.isModeCreate = isModeCreate;
`this.isModeCreate`

Б17
> Приватные и защищённые поля в классах **помечены** и не используются снаружи

2021-12-19 02:24 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
> +    this.element.querySelector('.event__rollup-btn').addEventListener('click', this.#clickHandler);
.event__`rollup-btn` + `click` !== this.#`click`Handler

> Напомню наперед: `btn` -> `Button` (Б4)

Д4
> Название обработчика строится следующим образом

> `(на каком элементе)` + `что случилось` + `Handler`

2021-12-19 02:24 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
> +    this._callback.formSubmit = callback;
this._callback.`formSubmit` = callback;

Нужно во всем проекте проверить похожие методы. (их очень много)

Б10
> Название функции или метода содержит глагол [в начале]

2021-12-19 02:24 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
> +    this.element.querySelector('.event__reset-btn').addEventListener('click', this.#deleteHandler);
.event__`reset-btn` + `click` !== this.#`delete`Handler

Д4

2021-12-19 02:24 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
> +    this.element.querySelector('.event__type-group').addEventListener('change', this.#changeTypeHandler);
.event__`type-group` + `change` !== this.#change`Type`Handler

Д4

2021-12-19 02:24 UTC, AlexMasterov commented on src/view/trip-point-view.js
> +    this.element.querySelector('.event__rollup-btn').addEventListener('click', this.#editClickHandler);
.event__`rollup-btn` + `click` !== this.#`edit`ClickHandler

Д4

2021-12-19 02:24 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
> +export default class FormCreateEditView extends AbstractView {
Д8
> Методы внутри классов упорядочены

```
2. Геттеры и сеттеры свойств класса
3. Основные методы класса:
4. Обработчики событий [DOM]
```

Нужно следуя этому критерия перегруппировать методы в классе.

> _Обычные_ методы с названием `set` / `get` тоже считаются "геттерами и сеттерами свойств класса" (2)

2021-12-19 02:34 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
<details>
<summary>view/form-create-edit-view.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/a5e792847fe814a261082a410fe213e80e60144d/src/view/form-create-edit-view.js#L111-L114
</details>

При создании новой точки маршрута можно выбрать направление с фото, но мы их не увидим 😄

<details>
<summary>view/form-create-edit-view.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/a5e792847fe814a261082a410fe213e80e60144d/src/view/form-create-edit-view.js#L116-L126
</details>

Если массив с фото пустой, то можно просто не нужно вызывать функцию.

Простая функция перегружена логикой, даже про `isModeCreate` знает 🤔

2021-12-19 02:36 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
<details>
<summary>view/form-create-edit-view.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/a5e792847fe814a261082a410fe213e80e60144d/src/view/form-create-edit-view.js#L108
</details>

({ src, description } `= {}`)

В текущей реализации и с учетом постоянной структуры данных подобное не требуется.

2021-12-19 02:37 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
См. ТЗ:
> При смене пункта назначения блок с описанием перерисовывается; **или скрывается**, если у пункта назначения нет описания **и** фотографий к нему

> Если информация о пункте назначения отсутствует, блок «Destination» не отображается

Можно попробовать доработать в этом задание.

2021-12-19 02:38 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
См. ТЗ:
> Список дополнительных опций доступен не для всех типов точек маршрута. Для некоторых типов точек дополнительные опции могут отсутствовать. **В этом случае контейнер для вывода дополнительных опций не отображается**

Можно доработать в этом задание.

2021-12-19 02:40 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
<details>
<summary>view/form-create-edit-view.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/a5e792847fe814a261082a410fe213e80e60144d/src/view/form-create-edit-view.js#L19-L21
</details>

Функция ничего не возвращает (= `undefined`).

Нужно исправить.

2021-12-19 02:43 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
> +    this._callback.changeType(evt);
this._callback.changeType(`evt`)

Это обработчик события _компонента_. Не нужно в него передавать _ссылку_ на объект события DOM.

2021-12-19 02:49 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
>  // import { allOffers } from '../mock/trip-point.js';
`//`

Нужно удалить.

Б18
> В коде проекта нет файлов и частей кода, которые не используются, включая закомментированные участки кода

2021-12-26 13:35 UTC, ifom1500 commented on src/utils/constants.js
> +export const DEFAULT_POINT = {
Можно ли оставить данный комментарий на разрешение на потом? Пока перенес DEFAULT_POINT в файл с моками как DEFAULT_POINT_DRAFT_DATE. Хочу разобраться с этим, когда буду работать с приходящими данными с сервера. Пока никак не складывается общая картина. И хочу еще подумать над вопросами:
- где правильнее парсить даты, так как даты будут приходить с сервера как строки, а я их парсю в объекте.
- где задавать дату для новой точки по умолчанию, если я хочу чтобы подставлялось текущее время

2021-12-26 13:38 UTC, ifom1500 commented on src/view/form-create-edit-view.js
> Если массив с фото пустой, то можно просто не нужно вызывать функцию.

Но если мы хотим создать новую точку, но для нее просто нет изображений? Все равно нужно ведь вызвать функцию `createPhotoContainerTemplate`, просто не показывать элемент с фотографиями в форме

2021-12-26 13:55 UTC, AlexMasterov commented on src/utils/constants.js
> +export const DEFAULT_POINT = {
> где правильнее парсить даты, так как даты будут приходить с сервера как строки, а я их парсю в объекте

При получении данных с сервера, "на границе приложения". 
В нашем случае это будет модуль API, а парсер будет находится в модели, которая соответствует данным.

> где задавать дату для новой точки по умолчанию, **если я хочу чтобы подставлялось текущее время**

1. Назвать переменную с объектом в `camelCase`, как обычную переменную, а не как "константу".
2. Создавать объект "по умолчанию" с помощью функции (вызов функции можно использовать в параметрах 
 в  качестве значения по умолчанию)

2021-12-26 13:55 UTC, AlexMasterov commented on src/utils/constants.js
> +export const DEFAULT_POINT = {
> Можно ли оставить данный комментарий на разрешение на потом?

Хорошо, но главное не забыть 😃

2021-12-26 13:58 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
> Но если мы хотим создать новую точку, но для нее просто нет изображений? **Все равно нужно ведь вызвать функцию `createPhotoContainerTemplate`**, просто не показывать элемент с фотографиями в форме

Повторю:
> Если массив с фото пустой, то можно просто не нужно вызывать функцию

Пример:
```js
${pictures.length > 0 ? createPhotoContainerTemplate(pictures)  : ''}
```

2021-12-26 14:14 UTC, AlexMasterov commented on src/utils/constants.js
> +  EDIT: !MODE_CREATE_TRUE,
🤔

> Пожалуй, что оставлю это на усмотрение случайного проверяющего на защите

2021-12-26 14:18 UTC, ifom1500 commented on src/utils/constants.js
> +  EDIT: !MODE_CREATE_TRUE,
Я просто не очень понял как можно так назвать константы, содержащие true или false значения. Сделал пока насколько понимаю :)

2021-12-26 14:24 UTC, AlexMasterov commented on src/utils/constants.js
> +  EDIT: !MODE_CREATE_TRUE,
<details>
<summary>view/form-create-edit-view.js</summary>

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/3551c79747938d6ff25344eb7b0becc1c689b523/src/view/form-create-edit-view.js#L236
</details>

constructor(point, destination, offers, `isModeCreate`) { 

Сейчас компонент использует _бинарный_ режим, что не очень, но в таком решение перечисление не нужно.

```diff
- constructor(point, destination, offers, `isModeCreate`) { 
+ constructor(point, destination, offers, isModeCreate = false) { 
```

```diff
- constructor(point, destination, offers, `isModeCreate`) { 
+ constructor(point, destination, offers, { isModeCreate = false } = {}) { 
```

```js
new FormCreateEditView(point, destinations, offers, { isModeCreate: true })
```

2021-12-26 14:25 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
>      this.#destination = destination;
```js
Array.isArray(destination) // true
```
Б8
> Массивы названы существительными во множественном числе

2021-12-26 14:26 UTC, merged