Module6 task1
htmlacademy-ecmascript/1849247-big-trip-16 pull request #8
Opened 2022-01-18 21:18 UTC by ifom1500

2022-01-23 14:23 UTC, ifom1500 commented on src/presenter/general-presenter.js
> +const BLANK_POINT = getBlankPoint(parseDate);
Продолжу работу над кнопкой и соответственно пустым объектом позже, в рамках соответствующей задачи.

2022-01-23 14:30 UTC, ifom1500 commented on src/view/form-create-edit-view.js
> +        const priceElement = labelElement.querySelector('.event__offer-price');
Есть ощущение, что такой поиск цены написан слишком громоздко. Решение работает, но подумаю позже как отрефакторить.

2022-01-23 14:33 UTC, ifom1500 commented on src/view/form-create-edit-view.js
> +    // debounce(() => this.updateData({basePrice: +evt.target.value}, true));
Хотел сделать изменение цены с дебаунсом, но таким образом функция не работает.
debounce() запускается, но коллбэк из return не возвращается. Что здесь не правильно может быть?

2022-01-23 14:36 UTC, ifom1500 commented
Нашел 2 бага в программе, пока не смог решить.
1 баг:
При закрытии формы редактирования точки нажатием Esc возникает ошибка:
![image](https://user-images.githubusercontent.com/77317082/150683688-eae51dc0-53c0-4d57-ab08-05e19351d52a.png)

2022-01-23 14:43 UTC, ifom1500 commented
2 баг
При открытии формы редактирования и выбора типа точки без офферов остается заголовок Offers
![image](https://user-images.githubusercontent.com/77317082/150683758-c2025065-d23c-46d4-8ebf-321629f6cb4e.png)

Если форму сохранить и открыть снова - заголовок пропадает. 

Затем если снова выбрать тип точки, где есть офферы, то блок с офферами не показывается сразу, а только если сохранить и заново открыть карточку.

Примерно понимаю в чем проблема (нужно не только обновлять data, но и перерисовывать всю форму), позже попробую исправить.

2022-01-23 16:15 UTC, AlexMasterov requested changes

2022-01-23 16:15 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
> +
```diff
+ delete point.destinationNames
```

2022-01-23 16:15 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/150687094-26d9597d-e155-48f4-a993-f6b1f8d9d4bc.png)

</details>

Например, если выбрать тип `taxi`, то отображается пустой блок `offers`.

См. ТЗ:
> Список дополнительных опций доступен не для всех типов точек маршрута. Для некоторых типов точек дополнительные опции могут отсутствовать. **В этом случае контейнер для вывода дополнительных опций не отображается**

> Про это говорили на консультации

Нужно доработать.

2022-01-23 16:15 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/150687323-58b836f4-f4c0-4fcb-9eb5-91ce4c7f8a43.png)

</details>

Если применить сортировку или добавить точку маршрута в избранное (= любая перерисовка точки маршрута), то кол. обработчиков `flatpickr` увеличивается, что ведет к утечке памяти.

Б36
> Обработчики события добавляются и удаляются своевременно

2022-01-23 16:15 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/150687359-bc121514-5d33-4e4d-ad7b-670ceac47e7c.png)

</details>

Если не закрывая форму редактирования открыть другую, то на `document` остается обработчик для `keydown`. После закрытии формы обработчики остаются и при открытии новой формы продолжают накапливаться.

Б36
> Обработчики события добавляются и удаляются своевременно

2022-01-23 16:15 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/150687505-b5ae180e-480d-4e66-b382-ca43ce27f39c.png)
</details>

См. ТЗ:
> Если информация о пункте назначения отсутствует, блок «Destination» не отображается

Нужно доработать.

2022-01-23 16:23 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
> +    // debounce(() => this.updateData({basePrice: +evt.target.value}, true));
В ТЗ нет требования для `debounce`. Зачем это нужно делать, тем более сейчас?

Интенсив заканчивается, нужно _за неделю_ успеть доработать хотя бы базовую часть ТЗ.

<details>
<summary>+ Модификация DOM в обработчике ввода — антипаттерн</summary>

![image](https://user-images.githubusercontent.com/700213/150687797-97603392-7277-4bad-87e6-67261a791b4e.png)
</details>

2022-01-23 16:29 UTC, AlexMasterov commented
> Нашел 2 бага в программе, пока не смог решить. 1 баг: При закрытии формы редактирования точки нажатием Esc возникает ошибка: ![image](https://user-images.githubusercontent.com/77317082/150683688-eae51dc0-53c0-4d57-ab08-05e19351d52a.png)

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/b42d11dec0e3097040120bc4edfb6dddc6099ea4/src/presenter/point-presenter.js#L125-L126

Род. элемент удаляется до обновления.

Нужно сделать как здесь: (т.е. поменять местами вызовы методов)

https://github.com/htmlacademy-ecmascript/1849247-big-trip-16/blob/b42d11dec0e3097040120bc4edfb6dddc6099ea4/src/presenter/point-presenter.js#L78-L79

2022-01-23 16:34 UTC, AlexMasterov commented
> 2 баг При открытии формы редактирования и выбора типа точки без офферов остается заголовок Offers ![image](https://user-images.githubusercontent.com/77317082/150683758-c2025065-d23c-46d4-8ebf-321629f6cb4e.png)
> 
> Если форму сохранить и открыть снова - заголовок пропадает.
> 
> Затем если снова выбрать тип точки, где есть офферы, то блок с офферами не показывается сразу, а только если сохранить и заново открыть карточку.
> 
> Примерно понимаю в чем проблема (нужно не только обновлять data, но и перерисовывать всю форму), позже попробую исправить.

При смене типа нужно на основе новый `offers` также обновить `isOffersExist`.

2022-01-23 20:03 UTC, ifom1500 commented on src/view/trip-point-view.js
> +    this._callback.favoriteButtonClick = callback;
Видимо не совсем понимаю данный критерий.
В критерии же есть исключение для функции колбэка. Тем более у меня в проекте есть подобные колбэки
`this._callback.formSubmit = callback;`

2022-01-23 21:50 UTC, ifom1500 commented on src/view/form-create-edit-view.js
> +
Не понимаю откуда надо удалять обработчики `flatpickr `. Вроде код аналогичен демо-проекту, но обработчики добавляются. Нужно где-то на этапе рендера удалять?

2022-01-24 05:39 UTC, AlexMasterov commented on src/view/trip-point-view.js
> +    this._callback.favoriteButtonClick = callback;
> На защите проекта _могут_ придраться

2022-01-24 05:39 UTC, merged

2022-01-24 06:18 UTC, AlexMasterov commented on src/view/form-create-edit-view.js
> +
Это баг самого `flatpickr`. Давно исправлено в `master`, но релиза еще нет. Указать в качестве версии конкретный коммит с исправлением мы не можем из-за критерия Б19. Для самостоятельного "исправления" можно использовать манки-патчинг или API DevTools, но это вызовет вопросы на защите.

Авторы курса в курсе про этот баг и его можно игнорировать.